package com.jbk.hibernate;
// Generated May 29, 2020 9:51:59 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "springapi")
public class Employee implements java.io.Serializable {

	@Override
	public String toString() {
		return "Employee [id=" + id + ", name=" + name + ", sname=" + sname + ", status=" + status + "]";
	}

	private Integer id;
	private String name;
	private String sname;
	private String status;

	public Employee() {
	}

	public Employee(String name, String sname, String status) {
		this.name = name;
		this.sname = sname;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sname", nullable = false, length = 45)
	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
